-- ucv_main.lua
-- Centralized logic for the Unit Color Variation (UCV) system.
-- code by Durzi/mentos987 (mostly LLM generated by gemini/claude)

--------------------------------------------------------------------------------
-- I. UTILITIES
--------------------------------------------------------------------------------

-- Split function for separators (like "--" or ":" in "scales:burner:ALBINO--eyes:burner:ALBINO")
local function split(str, sep)
    if sep == "" then 
		return {str}
	end
	local result = {}
    local start = 1
    while true do
        local pos = string.find(str, sep, start, true)
        if not pos then
            table.insert(result, string.sub(str, start))
            break
        end
        table.insert(result, string.sub(str, start, pos - 1))
        start = pos + string.len(sep)
    end
    return result
end

-- Check if a string is in a comma-separated string list (like "eyes" in "wings, eyes,feet")
local function is_in_list(value, list_string)
    if not list_string or list_string == "" then
        return true
    end
	for item in string.gmatch(list_string, "([^,]+)") do
        item = item:match("^%s*(.-)%s*$") -- trim whitespace
        if item == value then
            return true
        end
    end
    return false
end

-- Parses "body_part:archetype:color_variant" ID segments into a table/map
local function parse_composite_id(id_string)
    local map = {}
    local segments = split(id_string, "--")
    for _, segment in ipairs(segments) do
        local parts = split(segment, ":")
        if #parts == 3 then
            map[parts[1]] = parts[3] -- map[body_part] = color_variant
        end
    end
    return map
end

--------------------------------------------------------------------------------
-- II. CHECKERS
--------------------------------------------------------------------------------

-- Check if this unit should be color shifted. Check leaders and loyal units
local function should_exclude(unit)
    if wml.variables.modification_randomizer_no_loyal then
		if unit.canrecruit then -- Leader
			return true
		end
        local modifications = wml.get_child(unit.__cfg, "modifications")
        if modifications then
            for trait in wml.child_range(modifications, "trait") do
                if trait.id == "loyal" then -- Loyal trait
					return true 
				end
            end
        end
    end
    return false
end

-- Check if unusual colors are allowed
local function are_unusual_colors_enabled()
	return wml.variables.modification_randomizer_morphing
end

--------------------------------------------------------------------------------
-- III. CORE SEQUENCE
--------------------------------------------------------------------------------

-- Get UMC (User Made Content) frequency modifiers from stored WML adjustments
local function get_umc_modifiers(unit, body_part, variant)
    if not unit or not variant or not body_part then
		return 0, false
	end
	
    local total_adjustment = 0
    local override = false -- Should this variant be nullified? (odds set to 0% chance)
    local adjustments = wml.variables["UCV_change_color_frequency"] or {}
    
	-- Go over all UMC adjustments and see if any of them applies to our current unit, body_part and variant
    for i, wml_table in ipairs(adjustments) do
        local cfg = wml.literal(wml_table[2])
        local applies = true
        
        if cfg.sides then
            applies = applies and is_in_list(tostring(unit.side), tostring(cfg.sides))
        end
		
        if cfg.races then
            applies = applies and is_in_list(unit.race, tostring(cfg.races))
        end
		
        if cfg.body_parts then
            applies = applies and is_in_list(body_part, tostring(cfg.body_parts))
        end
		
		-- Check override for all variants that fulfill the sides/races/body_parts criteria
		if applies and cfg.override_others and (cfg.override_others == true or cfg.override_others == "yes" or cfg.override_others == "true") then
			override = true
        end

		if cfg.variants then
            applies = applies and is_in_list(variant, tostring(cfg.variants))
		else
			applies = false -- variants is/are required
        end
		
		if applies and cfg.adjust_frequency then
			local adjust = tonumber(cfg.adjust_frequency) or 0
			total_adjustment = total_adjustment + adjust
		end
    end
    
    return total_adjustment, override
end

-- Weighted Random Choice with frequency adjustment from affinities and UMC input
local function get_weighted_choice(variants, affinity_modifiers, allow_rare, unit, body_part)
    local pool = {}
    local total_weight = 0
	
    for variant, data in pairs(variants) do
	
        local weight = data.frequency or 1.0
        
		-- Apply affinity modifiers from previous parts
        if affinity_modifiers[variant] then
			weight = weight + affinity_modifiers[variant] 
		end
		
        -- Apply UMC (User Made Content) modifiers from saved WML table
        local umc_adjustment, override_others = get_umc_modifiers(unit, body_part, variant)
        if override_others then
            weight = 0
        end
        weight = weight + umc_adjustment
        
		if umc_adjustment == 0 and override_others == false and	data.rare and not allow_rare then
			weight = 0
		end
		if umc_adjustment == 0 and override_others == false and	should_exclude(unit) then
			weight = 0
		end
		
		-- Add variant to the pool of options
        if weight > 0 then
            table.insert(pool, {variant = variant, data = data, weight = weight})
            total_weight = total_weight + weight
        end

    end
	
    if total_weight <= 0 then 
		return nil 
	end
	
	-- Pick a random variant from the pool and return it
    local roll = mathx.random() * total_weight
    local current_sum = 0
    for _, entry in ipairs(pool) do
        current_sum = current_sum + entry.weight
        if roll <= current_sum then
			return entry
		end
    end
end

-- Core engine that builds the palette and the ID
local function generate_ucv_data(unit, old_variants_map, allow_rare)
    old_variants_map = old_variants_map or {}
    local race_data = _G.ucv_race_registry[unit.race]
    if not race_data or not race_data.body_parts then 
		return nil 
	end

    local affinity_modifiers = {} 
    local base_palettes_table = {}
    local new_palettes_table = {}
    local id_parts = {}
	
	-- Iterate body parts (e.g. "scales, weapon ..")
    for _, body_part_entry in pairs(race_data.body_parts) do
		local body_part = body_part_entry.name
		
		-- Iterate archetypes (e.g., "glider, fighter ..")
        for archetype, archetype_data in pairs(body_part_entry.data) do
            
			 -- Check if this sub-group applies to this unit type
			local applies = false
            for _, utype in ipairs(archetype_data.unit_types or {}) do
                if utype == unit.type then 
					applies = true; 
					break 
				end
            end
			
            if applies then
			
				-- Extract variants (e.g., "BROWN, INFERNO ..")
                local variants = {}
                for k, v in pairs(archetype_data) do
                    if k ~= "unit_types" then 
						variants[k] = v 
					end
                end

                local chosen = nil
                local target_variant_id = old_variants_map[body_part]

                -- Pick variant. Keep old variant when leveling up if it exists in the new part, else randomize.
                if target_variant_id and variants[target_variant_id] then
                    chosen = { variant = target_variant_id, data = variants[target_variant_id] }
                else
                    local affinity_mod = affinity_modifiers[body_part] or {}
                    chosen = get_weighted_choice(variants, affinity_mod, allow_rare, unit, body_part)
                end
				
				--Apply the chosen variant of the body part
                if chosen then
                    table.insert(id_parts, string.format("%s:%s:%s", body_part, archetype, chosen.variant))
                    
                    -- Apply visual "affinity" or "style matching" to future body parts by rearanging future weigths. e.g. Albino scales affects odds of getting albino eyes.
                    if chosen.data.affinity then
                        for target_part, target_vars in pairs(chosen.data.affinity) do
                            affinity_modifiers[target_part] = affinity_modifiers[target_part] or {}
                            for var_id, frequency_mod in pairs(target_vars) do
                                affinity_modifiers[target_part][var_id] = (affinity_modifiers[target_part][var_id] or 0) + frequency_mod
                            end
                        end
                    end

                    -- Compile palettes. Add to the base and target color, but only if the new color isn't same as base color.
					-- palette is a string of HEX colors like "414141,FF0000"
                    local source_palette = archetype_data.BASE and archetype_data.BASE.colors
                    local target_palette = chosen.data.colors
                    if source_palette and target_palette and chosen.variant ~= "BASE" then
                        table.insert(base_palettes_table, source_palette)
                        table.insert(new_palettes_table, target_palette)
                    end
					
                    break -- move to next body_part
                end
            end
        end
    end

    return {
		-- Combine the tables into strings and return them
        id = table.concat(id_parts, "--"),	-- "scales:burner:ALBINO--eyes:burner:ALBINO"
        base_colors = table.concat(base_palettes_table, ","), -- "989898,6E6E6E,414141,414141,222222"	
        new_colors = table.concat(new_palettes_table, ",") -- -- "A5876D,745B52,573D2D,65564B,324634"	
    }
end

-- Applies the final modification in the game
local function apply_ucv_to_unit(unit, ucv_data, old_id_to_remove)

    -- Remove existing UCV object if any exists
    if old_id_to_remove then
        unit:remove_modifications({ ucv_color_id = old_id_to_remove }, "object")
    end
	
	-- Create a new object that applies the color change for the unit
    local mod = { ucv_color_id = ucv_data.id }
    if ucv_data.base_colors ~= "" and ucv_data.new_colors ~= "" then
        table.insert(mod, { "effect", {
            apply_to = "image_mod",
            add = string.format("~PAL(%s>%s)", ucv_data.base_colors, ucv_data.new_colors)
        }})
    end
    unit:add_modification("object", mod)
	
	--In game it looks like:
	--	[object]
	--		ucv_color_id="scales:burner:ALBINO--eyes:burner:ALBINO"
	--		[effect]
	--			add="~PAL(DEB099,A5876D,745B52,573D2D,65564B,324634,2C2E12,40513C,4C3324,F3A62C,FFF200,F7DF8E,C79962>CCCCCC,989898,6E6E6E,414141,414141,222222,222222,373432,373432,FF0000,FF7762,DEDEDE,A4988F)"
	--			apply_to="image_mod"
	--		[/effect]
	--	[/object]
end

--------------------------------------------------------------------------------
-- IV. EVENTS
--------------------------------------------------------------------------------
local on_event = wesnoth.require("on_event")

-- Handle a unit being spawned/recruited/recalled.
on_event("unit placed", function(ctx)
    local unit = wesnoth.units.get(ctx.x1, ctx.y1)
    if not unit then 
		return
	end
    
    -- Skip if it already has a color shift
    local modifications = wml.get_child(unit.__cfg, "modifications")
    if modifications then
        for adv in wml.child_range(modifications, "object") do
            if adv.ucv_color_id then 
				return
			end
        end
    end
	
	local allow_rare = are_unusual_colors_enabled()
	
    local data = generate_ucv_data(unit, nil, allow_rare)
	if data then
		apply_ucv_to_unit(unit, data)
	end
end)

-- Handle a unit leveling up.
on_event("post advance", function(ctx)
    local unit = wesnoth.units.get(ctx.x1, ctx.y1)
    if not unit then 
		return
	end
	
	-- Get old color id so we can keep the new colors consistant with the old one.
    local old_color_id = nil
    local modifications = wml.get_child(unit.__cfg, "modifications")
    if modifications then
        for adv in wml.child_range(modifications, "object") do
            if adv.ucv_color_id then
                old_color_id = adv.ucv_color_id
                break
            end
        end
    end

	local allow_rare = are_unusual_colors_enabled()

    if old_color_id then
        local old_variants = parse_composite_id(old_color_id)
        local data = generate_ucv_data(unit, old_variants, allow_rare)
        apply_ucv_to_unit(unit, data, old_color_id)
	--else
	--	local allow_rare = are_unusual_colors_enabled()
	--	local data = generate_ucv_data(unit, nil, allow_rare)
	--	apply_ucv_to_unit(unit, data)
    end
end)

--------------------------------------------------------------------------------
-- V. WML ACTIONS
--------------------------------------------------------------------------------

-- Take in UMC input about altering frequencies and store it in a WML table that will later be applied when picking between variants
function wesnoth.wml_actions.UCV_change_color_frequency(cfg)
    
	-- Count existing entries
	local count = 0
    if wml.variables["UCV_change_color_frequency"] then
        for _ in ipairs(wml.variables["UCV_change_color_frequency"]) do
            count = count + 1
        end
    end
    
    -- Append the new adjustment at the next index
    wml.variables["UCV_change_color_frequency." .. count] = wml.literal(cfg)
end

-- wesnoth.interface.add_chat_message("loyal!")